"""
Demo script showing the LangGraph text-to-SQL agent workflow
This demonstrates the agent's functionality without requiring an OpenAI API key
"""
from text_to_sql_agent import get_database_schema, execute_sql
from sqlalchemy import create_engine
import os

def demo_agent_workflow():
    """Demonstrate the complete agent workflow"""
    print("=" * 80)
    print("🤖 LangGraph Text-to-SQL Agent Demo")
    print("=" * 80)
    
    # Step 1: Get database schema
    print("\n步骤 1: 获取数据库结构 / Step 1: Get database schema")
    print("-" * 80)
    schema = get_database_schema()
    print(schema)
    
    # Step 2: Demonstrate SQL generation (simulated)
    print("\n\n步骤 2: 生成 SQL 查询 / Step 2: Generate SQL queries")
    print("-" * 80)
    
    # Example queries that would be generated by the LLM
    example_queries = [
        {
            "question": "显示所有用户 / Show all users",
            "sql": "SELECT * FROM users"
        },
        {
            "question": "找出购买了笔记本电脑的用户 / Find users who bought laptops",
            "sql": """SELECT DISTINCT u.name, u.email
FROM users u
JOIN orders o ON u.id = o.user_id
JOIN products p ON o.product_id = p.id
WHERE p.name LIKE '%笔记本电脑%'"""
        },
        {
            "question": "统计每个产品的总销量 / Count total sales for each product",
            "sql": """SELECT p.name, SUM(o.quantity) as total_sales
FROM products p
JOIN orders o ON p.id = o.product_id
GROUP BY p.name
ORDER BY total_sales DESC"""
        },
        {
            "question": "显示价格最高的3个产品 / Show top 3 most expensive products",
            "sql": "SELECT name, price, category FROM products ORDER BY price DESC LIMIT 3"
        }
    ]
    
    # Step 3: Execute queries and show results
    for i, example in enumerate(example_queries, 1):
        print(f"\n{'=' * 80}")
        print(f"示例 {i} / Example {i}")
        print(f"{'=' * 80}")
        print(f"\n用户问题 / User Question:")
        print(f"  {example['question']}")
        print(f"\n生成的 SQL / Generated SQL:")
        print(f"  {example['sql']}")
        print(f"\n查询结果 / Query Results:")
        print("-" * 80)
        
        # Execute the query
        state = {
            "sql_query": example['sql'],
            "error": ""
        }
        result_state = execute_sql(state)
        
        if result_state.get("error"):
            print(f"❌ {result_state['error']}")
        else:
            print(result_state["query_result"])
    
    print(f"\n{'=' * 80}")
    print("✅ Demo completed successfully!")
    print("=" * 80)
    print("\n📝 注意 / Note:")
    print("  要使用完整的智能体功能，需要配置 OPENAI_API_KEY 环境变量")
    print("  To use the full agent functionality, configure the OPENAI_API_KEY environment variable")
    print("\n  然后运行 / Then run:")
    print("    python cli.py")
    print("=" * 80)


if __name__ == "__main__":
    demo_agent_workflow()
